### ISSUE TITLE
Add 'visual-studio-code' as 'code' to $PATH for "ubuntu make method"

### ISSUE THREAD

**Issue by todthomson** [todthomson/linux-dotnetcore-docker-how-to#10]
As per suggestion from Gitter by @mateuszligeza

```
export PATH=$PATH:/home/mat/.local/share/umake/ide/visual-studio-code
```

Or as suggested on Gitter by @ShawInnes

```
printf "code() {\n  ~/.local/share/umake/ide/visual-studio-code/code --disable-gpu $@ \n}" >> ~/.bashrc
```

Or as suggested on Gitter by @nblumhardt

More information about Ubuntu Make here: https://wiki.ubuntu.com/ubuntu-make

OR just remove the "Ubuntu Make Method" as it seems superfluous?

More info here: http://askubuntu.com/questions/616075/how-to-install-visual-studio-code-on-ubuntu

**Comment by todthomson** [comment]
This is no longer required as I have removed the Ubuntu Make method from the workshop as it just added too much confusion for the value it provided.

**Comment by robgrzel** [comment]
In /home/robgrzel/.local/share/umake/bin/ just copy visual-studio-code link to new link code
