### ISSUE TITLE
Add "Chapter 8" on OmniSharp

### ISSUE THREAD

**Issue by todthomson** [todthomson/linux-dotnetcore-docker-how-to#28]
http://www.omnisharp.net

**Comment by mateuszligeza** [comment]
@todthomson I couldn't get OmniSharp to work with VS Code using Ubuntu 16.04.1

It seems some packages needed for it to work are not present in this version of Ubuntu. I got it to work on Ubuntu 14.04.4 LTS. I also had to install node and resolve some Ubuntu naming problems:

> On Ubuntu, there’s already a tool called “Node” that would otherwise cause a name conflict

Full article that helped me resolve the problem you can find here: [http://truthyfalsey.com/yeoman-working-ubuntu/](http://truthyfalsey.com/yeoman-working-ubuntu/)

I resolved this issue on the weekend after your presentation in Brisbane and deleted the image afterwards, so I don't have full history of the commands I used, but I hope this will help you.

**Comment by todthomson** [comment]
Closing (as I am considering this tutorial done/deprecated/abandoned).
