### ISSUE TITLE
VS Code "launcher" needs --disable-gpu to work in Virtual Box

### ISSUE THREAD

**Issue by JonCB** [todthomson/linux-dotnetcore-docker-how-to#8]
If you've got a launcher icon that opens without disable-gpu you can update the icon to add the parameter.

From terminal :- 
cd ~/.local/share/applications
nano visual-studio-code.desktop

then find the Exec= line and add --disable-gpu to the end.

**Comment by todthomson** [comment]
Thanks :) I'll update the guide asap!

**Comment by todthomson** [comment]
Guide updated :) thanks again @JonCB
